### ISSUE TITLE
I'm getting back a html error

### ISSUE THREAD

**Issue by otienoelvis** [BettingApi/docs#1]
please help

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Cannot GET /football/line/league/matches</pre>
    </body>
</html>

**Comment by zvs001** [comment]
@donFalconJefe 
Url is not correct. You forget to add `league_id` to url
Vlid url looks like: `/football/line/league/:league_id/matches`

You can get league_id from routes: 
- `/football/line/leagues` 
- `/football/live/leagues`

**Comment by otienoelvis** [comment]
Thank you, it worked
